// Orbital Prospect: a neon asteroid-mining outfit drilling rocks in the belt.
ThemeKit.register({
  id: "orbital-prospect",
  name: "Orbital Prospect",
  author: "Claude",
  title: "Orbital Prospect Ltd.",
  fonts: "https://fonts.googleapis.com/css2?family=Orbitron:wght@600;800&family=Share+Tech+Mono&display=swap",
  labels: {
    "#use-hint": "Deep<br>Scan",
    "#auto-miners-button": "Drone<br>Swarm",
  },
  phrases: {
    // Company and glyphs
    "Sweeper Inc.": "Orbital Prospect Ltd.",
    "Sweeper Inc": "Orbital Prospect Ltd",
    "arcade minesweeper": "asteroid minesweeper",
    "Arcade controls": "Cockpit controls",
    "Cabinet mode controls": "Ship mode controls",
    "✹": "✷",
    "⚑": "▲",
    "✦": "◆",
    "◆": "⌬",
    "⛏": "⬡",
    "★": "✧",
    "▣": "⊞",
    "$": "₡",

    // Hazards and rewards
    "Mine Encapsulation": "Stasis Capture",
    "Mine Curio": "Xeno Artifact",
    "Mine Yield": "Volatile Harvest",
    "Mine yield": "Volatile harvest",
    "mine recovery": "volatile harvesting",
    "Auto Miners": "Mining Drones",
    "Auto Miner": "Mining Drone",
    "Auto Mine": "Drone Swarm",
    "Mines": "Volatiles",
    "Mine": "Volatile",
    "mines": "volatiles",
    "mine": "volatile",
    "Treasures": "Crystals",
    "Treasure": "Crystal",
    "treasures": "crystals",
    "treasure": "crystal",
    "Richer Caches": "Richer Lodes",
    "Richer caches": "Richer lodes",
    "caches": "lodes",
    "cache": "lode",
    "chests": "geodes",
    "chest": "geode",
    "Boom.": "Breach!",

    // Tools
    "The shovel shattered": "The drill bit fractured",
    "Shovel Locker": "Bit Magazine",
    "Shovels": "Drill Bits",
    "Shovel": "Drill Bit",
    "shovels": "drill bits",
    "shovel": "drill bit",
    "digs": "bores",
    "dig": "bore",
    "Digging": "Boring",
    "digging": "boring",
    "Wooden": "Carbon",
    "Iron": "Ferrite",
    "Obsidian": "Graphene",
    "Diamond": "Neutronium",
    "Flag Locker": "Beacon Bay",
    "Flagbearer": "Beacon Drone",
    "Flags": "Beacons",
    "Flag": "Beacon",
    "flags": "beacons",
    "flag": "beacon",
    "flagged": "beaconed",
    "Hints": "Scans",
    "Hint": "Scan",
    "hints": "scans",
    "hint": "scan",
    "Probe Charge": "Probe Drone",
    "Controlled Blast": "Plasma Burst",
    "Seismic Trap": "Gravimetric Scan",
    "Bomb-Bot": "Shield Drone",
    "Special Equipment": "Tech Modules",
    "Equipment": "Modules",
    "equipment": "modules",

    // Places and panels
    "Quartermaster": "Supply Depot",
    "Supplies": "Consumables",
    "supplies": "consumables",
    "Workshop": "Fabricator",
    "Upgrades": "Mods",
    "Upgrade": "Mod",
    "upgrades": "mods",
    "Abilities": "Protocols",
    "Ability": "Protocol",
    "Purse": "Credits",
    "Coins": "Credits",
    "Claims Desk": "Comms",
    "Message Board": "Comm Relay",
    "Contracts": "Bounties",
    "Contract": "Bounty",
    "contracts": "bounties",
    "contract": "bounty",
    "Challenges": "Directives",
    "Challenge": "Directive",
    "Finds": "Artifacts",
    "Curios": "Artifacts",
    "Curio": "Artifact",
    "curios": "artifacts",
    "Operator Panel": "Ship Console",
    "Settings": "Systems",
    "Ledger": "Flight Log",
    "Statistics": "Telemetry",
    "Corporate Restructuring": "Corporate Jump",
    "Restructure": "Engage Jump",
    "Delete All Progress": "Self-Destruct",
    "High Score": "Top Yield",
    "District Crew": "Belt Crew",
    "District": "Belt Map",
    "Camp Parcel": "Outpost Rock",
    "Establish a Camp": "Establish an Outpost",
    "Camp": "Outpost",
    "Parcels": "Asteroids",
    "Parcel": "Asteroid",
    "parcels": "asteroids",
    "parcel": "asteroid",
    "Field Specification": "Scan Profile",
    "Field Spec": "Scan Profile",
    "Field value": "Rock value",
    "Field Cleared": "Rock Cleared",
    "Field": "Rock",
    "Board Setup": "Scan Profile",
    "Boards": "Rocks",
    "Board": "Rock",
    "boards": "rocks",
    "board": "rock",
    "Runs": "Expeditions",
    "Run": "Expedition",
    "Sweep the grid": "Survey the rock",

    // Crew
    "Surveyors": "Scouts",
    "Surveyor": "Scout",
    "Excavator": "Borer",
    "Analyst": "Navigator AI",
    "Specialists": "Engineers",
    "Agents": "Drones",
    "Blueprint Library": "Pattern Database",

    // Contract sites and parcels
    "Abandoned Yard": "Derelict Hauler",
    "Coal Seam": "Carbon Belt",
    "Flooded Quarry": "Ice Moon Quarry",
    "Crystal Cavern": "Crystal Geode",
    "Ruined Armory": "Wrecked Dreadnought",
    "Battlefield": "Debris Field",
    "Abandoned Quarry": "Derelict Quarry",
    "Iron Seam": "Nickel-Iron Core",
    "Collapsed Tunnel": "Fractured Shaft",
    "Crystal Chamber": "Crystal Vug",
    "Old Military Arsenal": "Old Weapons Platform",
    "Gold Vein": "Platinum Vein",
    "Unstable Fault": "Tidal Fracture",
    "Loose Sediment": "Loose Regolith",
    "Bedrock": "Dense Core",
    "Flooded Pocket": "Ice Pocket",
    "Manual Sweep": "Manual Override",
    "Rush Job": "Burn Window",

    // Cabinet button states
    "READY": "LAUNCH",
    "RETRY": "RELAUNCH",
    "DONE": "DOCKED",
    "AGAIN": "LAUNCH",
    "LOCKED": "OFFLINE",
  },
});
