// Abyssal Salvage: a deep-sea salvage outfit sweeping sunken minefields by sonar.
ThemeKit.register({
  id: "abyssal-salvage",
  name: "Abyssal Salvage",
  author: "Claude",
  title: "Abyssal Salvage Co.",
  fonts: "https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@500;700&family=IBM+Plex+Mono:wght@400;600&display=swap",
  phrases: {
    // Company and glyphs
    "Sweeper Inc.": "Abyssal Salvage Co.",
    "Sweeper Inc": "Abyssal Salvage Co",
    "arcade minesweeper": "sonar minesweeper",
    "Arcade controls": "Helm controls",
    "Cabinet mode controls": "Submersible mode controls",
    "✹": "✺",
    "⚑": "⚓",
    "✦": "◉",
    "◆": "✾",
    "⛏": "◍",
    "★": "≋",
    "▣": "⚙",
    "$": "Ð",

    // Hazards and rewards
    "Mine Encapsulation": "Mine Netting",
    "Mine Curio": "Wreck Relic",
    "Mine Yield": "Disarm Bounty",
    "Mine yield": "Disarm bounty",
    "mine recovery": "mine disarming",
    "Auto Miners": "Salvage Drones",
    "Auto Miner": "Salvage Drone",
    "Auto Mine": "Drone Sweep",
    "Mines": "Sea Mines",
    "Mine": "Sea Mine",
    "mines": "sea mines",
    "mine": "sea mine",
    "Treasures": "Pearls",
    "Treasure": "Pearl",
    "treasures": "pearls",
    "treasure": "pearl",
    "Richer Caches": "Richer Oyster Beds",
    "Richer caches": "Richer oyster beds",
    "caches": "oyster beds",
    "cache": "oyster bed",
    "chests": "clams",
    "chest": "clam",
    "Boom.": "Detonation.",

    // Tools
    "The shovel shattered": "The dive tank flooded",
    "Shovel Locker": "Tank Rack",
    "Shovels": "Dive Tanks",
    "Shovel": "Dive Tank",
    "shovels": "dive tanks",
    "shovel": "dive tank",
    "digs": "dives",
    "dig": "dive",
    "Digging": "Diving",
    "digging": "diving",
    "Wooden": "Canvas",
    "Copper": "Brass",
    "Obsidian": "Abyssal",
    "Diamond": "Nautilus",
    "Flag Locker": "Buoy Rack",
    "Flagbearer": "Buoy Tender",
    "Flags": "Buoys",
    "Flag": "Buoy",
    "flags": "buoys",
    "flag": "buoy",
    "flagged": "buoyed",
    "Hints": "Sonar Pings",
    "Hint": "Sonar Ping",
    "hints": "sonar pings",
    "hint": "sonar ping",
    "Probe Charge": "Sonar Buoy",
    "Controlled Blast": "Depth Charge",
    "Seismic Trap": "Hydrophone Array",
    "Bomb-Bot": "Decoy Drone",
    "Special Equipment": "Deep Gear",
    "Equipment": "Gear",
    "equipment": "gear",

    // Places and panels
    "Quartermaster": "Chandlery",
    "Supplies": "Provisions",
    "supplies": "provisions",
    "Workshop": "Dry Dock",
    "Upgrades": "Refits",
    "Upgrade": "Refit",
    "upgrades": "refits",
    "Abilities": "Techniques",
    "Ability": "Technique",
    "Purse": "Salvage Fund",
    "Coins": "Doubloons",
    "Claims Desk": "Harbor Master",
    "Message Board": "Radio Room",
    "Contracts": "Charters",
    "Contract": "Charter",
    "contracts": "charters",
    "contract": "charter",
    "Challenges": "Trials",
    "Challenge": "Trial",
    "Finds": "Reef Finds",
    "Curios": "Relics",
    "Curio": "Relic",
    "curios": "relics",
    "Operator Panel": "Bridge",
    "Settings": "Helm",
    "Ledger": "Ship's Log",
    "Statistics": "Log Book",
    "Corporate Restructuring": "Refit the Fleet",
    "Restructure": "Refit Fleet",
    "Delete All Progress": "Scuttle the Company",
    "High Score": "Deepest Haul",
    "District Crew": "Salvage Crew",
    "District": "Seabed Chart",
    "Camp Parcel": "Moonpool Site",
    "Establish a Camp": "Drop a Moonpool",
    "Camp": "Moonpool",
    "Parcels": "Wreck Sites",
    "Parcel": "Wreck Site",
    "parcels": "wreck sites",
    "parcel": "wreck site",
    "Field Specification": "Dive Plan",
    "Field Spec": "Dive Plan",
    "Field value": "Haul value",
    "Field Cleared": "Trench Cleared",
    "Field": "Trench",
    "Board Setup": "Dive Plan",
    "Boards": "Dives",
    "Board": "Dive",
    "boards": "dives",
    "board": "dive",
    "Runs": "Voyages",
    "Run": "Voyage",
    "Sweep the grid": "Sweep the trench",

    // Crew
    "Surveyors": "Sonar Techs",
    "Surveyor": "Sonar Tech",
    "Excavator": "ROV Pilot",
    "Analyst": "Chart Reader",
    "Specialists": "Divers",
    "Agents": "Deckhands",
    "Blueprint Library": "Chart Library",

    // Contract sites and parcels
    "Abandoned Yard": "Sunken Barge",
    "Coal Seam": "Kelp Forest",
    "Flooded Quarry": "Drowned Harbor",
    "Crystal Cavern": "Coral Grotto",
    "Ruined Armory": "Wrecked Destroyer",
    "Battlefield": "Convoy Graveyard",
    "Abandoned Quarry": "Sunken Quarry",
    "Iron Seam": "Iron Wreck",
    "Collapsed Tunnel": "Collapsed Hull",
    "Crystal Chamber": "Pearl Chamber",
    "Old Military Arsenal": "Old Naval Arsenal",
    "Gold Vein": "Galleon Hold",
    "Unstable Fault": "Thermal Vent",
    "Loose Sediment": "Silt Flat",
    "Flooded Pocket": "Air Pocket",
    "Manual Sweep": "Hand Sweep",
    "Rush Job": "Tide Race",

    // Cabinet button states
    "READY": "DIVE",
    "RETRY": "REDIVE",
    "DONE": "SURFACED",
    "AGAIN": "DIVE",
    "LOCKED": "SEALED",
  },
});
