// Brass & Soot Colliery: a Victorian mining company with pickaxes, canaries, and gas lamps.
ThemeKit.register({
  id: "brass-colliery",
  name: "Brass & Soot Colliery",
  author: "Claude",
  title: "Brass & Soot Colliery Co.",
  fonts: "https://fonts.googleapis.com/css2?family=Cinzel:wght@600;800&family=Special+Elite&display=swap",
  labels: {
    "#use-hint": "Send<br>Canary",
    "#auto-miners-button": "Clockwork<br>Crew",
  },
  phrases: {
    // Company and glyphs
    "Sweeper Inc.": "Brass & Soot Colliery Co.",
    "Sweeper Inc": "Brass & Soot Colliery Co",
    "arcade minesweeper": "colliery minesweeper",
    "Arcade controls": "Pithead controls",
    "Cabinet mode controls": "Winding-house controls",
    "✹": "♨",
    "⚑": "⚠",
    "✦": "❖",
    "◆": "⚜",
    "⛏": "⚒",
    "★": "⚙",
    "▣": "✠",
    "$": "£",

    // Hazards and rewards
    "Mine Encapsulation": "Gas Bottling",
    "Mine Curio": "Colliery Curiosity",
    "Mine Yield": "Gas Bounty",
    "Mine yield": "Gas bounty",
    "mine recovery": "gas capture",
    "Auto Miners": "Automatons",
    "Auto Miner": "Automaton",
    "Auto Mine": "Clockwork Crew",
    "Mines": "Gas Pockets",
    "Mine": "Gas Pocket",
    "mines": "gas pockets",
    "mine": "gas pocket",
    "Treasures": "Gold Nuggets",
    "Treasure": "Gold Nugget",
    "treasures": "gold nuggets",
    "treasure": "gold nugget",
    "Richer Caches": "Richer Reefs",
    "Richer caches": "Richer reefs",
    "caches": "reefs",
    "cache": "reef",
    "chests": "strongboxes",
    "chest": "strongbox",
    "Boom.": "Firedamp!",

    // Tools
    "The shovel shattered": "The pickaxe shattered",
    "Shovel Locker": "Tool Rack",
    "Shovels": "Pickaxes",
    "Shovel": "Pickaxe",
    "shovels": "pickaxes",
    "shovel": "pickaxe",
    "digs": "swings",
    "dig": "swing",
    "Digging": "Hewing",
    "digging": "hewing",
    "Flag Locker": "Lamp Room",
    "Flagbearer": "Lamplighter",
    "Flags": "Warning Lamps",
    "Flag": "Warning Lamp",
    "flags": "warning lamps",
    "flag": "warning lamp",
    "flagged": "lamped",
    "Hints": "Canaries",
    "Hint": "Canary",
    "hints": "canaries",
    "hint": "canary",
    "Probe Charge": "Safety Lamp Probe",
    "Controlled Blast": "Black Powder Blast",
    "Seismic Trap": "Seismograph",
    "Bomb-Bot": "Clockwork Sapper",
    "Special Equipment": "Patent Apparatus",
    "Equipment": "Apparatus",
    "equipment": "apparatus",

    // Places and panels
    "Quartermaster": "Company Store",
    "Supplies": "Stores",
    "supplies": "stores",
    "Workshop": "Foundry",
    "Upgrades": "Improvements",
    "Upgrade": "Improvement",
    "upgrades": "improvements",
    "Abilities": "Methods",
    "Ability": "Method",
    "Purse": "Strongbox",
    "Coins": "Sovereigns",
    "Claims Desk": "Wires",
    "Message Board": "Telegraph Office",
    "Contracts": "Commissions",
    "Contract": "Commission",
    "contracts": "commissions",
    "contract": "commission",
    "Challenges": "Wagers",
    "Challenge": "Wager",
    "Finds": "Curiosities",
    "Curios": "Curiosities",
    "Curio": "Curiosity",
    "curios": "curiosities",
    "Operator Panel": "Engine Room",
    "Settings": "Controls",
    "Ledger": "Account Book",
    "Statistics": "Tallies",
    "Corporate Restructuring": "Company Reorganisation",
    "Restructure": "Reorganise",
    "Delete All Progress": "Dissolve the Company",
    "High Score": "Record Haul",
    "District Crew": "Pit Crew",
    "District": "Survey Map",
    "Camp Parcel": "Pithead Claim",
    "Establish a Camp": "Sink a Pithead",
    "Camp": "Pithead",
    "Parcels": "Claims",
    "Parcel": "Claim",
    "parcels": "claims",
    "parcel": "claim",
    "Field Specification": "Seam Survey",
    "Field Spec": "Seam Survey",
    "Field value": "Seam value",
    "Field Cleared": "Seam Cleared",
    "Field": "Seam",
    "Board Setup": "Seam Survey",
    "Boards": "Shafts",
    "Board": "Shaft",
    "boards": "shafts",
    "board": "shaft",
    "Runs": "Shifts",
    "Run": "Shift",
    "Sweep the grid": "Work the seam",

    // Crew
    "Surveyors": "Deputies",
    "Surveyor": "Deputy",
    "Excavator": "Hewer",
    "Analyst": "Engineer",
    "Specialists": "Tradesmen",
    "Agents": "Pit Lads",
    "Blueprint Library": "Drafting Room",

    // Contract sites and parcels
    "Abandoned Yard": "Abandoned Pithead",
    "Coal Seam": "Barnsley Seam",
    "Flooded Quarry": "Flooded Adit",
    "Crystal Cavern": "Quartz Gallery",
    "Ruined Armory": "Ruined Powder Magazine",
    "Battlefield": "Old Workings",
    "Abandoned Quarry": "Disused Quarry",
    "Iron Seam": "Ironstone Seam",
    "Collapsed Tunnel": "Collapsed Gallery",
    "Crystal Chamber": "Quartz Chamber",
    "Old Military Arsenal": "Old Powder Store",
    "Gold Vein": "Gold Reef",
    "Unstable Fault": "Creeping Fault",
    "Loose Sediment": "Loose Spoil",
    "Flooded Pocket": "Sump",
    "Manual Sweep": "Hand Hewing",
    "Rush Job": "Double Shift",

    // Cabinet button states
    "READY": "STOKE",
    "RETRY": "AGAIN",
    "DONE": "CLOCKED",
    "AGAIN": "STOKE",
    "LOCKED": "BOLTED",
  },
});
