// Presentation only. Title-case entries precede lowercase variants.
ThemeKit.register({
  "id": "sugar-works",
  "name": "Sugar Works",
  "author": "Codex",
  "title": "Sugar Works | Confectionery",
  "fonts": "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600;9..144,700&family=Nunito:wght@400;600;700;800&display=swap",
  "labels": {
    "#use-hint": "Taste<br>Test",
    "#auto-miners-button": "Auto<br>Bake",
    "#district-button": "Factory<br>Map",
    ".marquee h1": "Sugar Works"
  },
  "phrases": {
    "Sweeper Inc.": "Sugar Works Confectionery",
    "Sweeper Inc": "Sugar Works Confectionery",
    "Mines": "Sour Drops",
    "Mine": "Sour Drop",
    "Treasures": "Truffles",
    "Treasure": "Truffle",
    "Chests": "Candy Boxes",
    "Chest": "Candy Box",
    "Caches": "Bonbon Batches",
    "Cache": "Bonbon Batch",
    "Richer Caches": "Richer Bonbon Batches",
    "Flags": "Cherry Markers",
    "Flag": "Cherry Marker",
    "Flag Locker": "Cherry Jar",
    "Flagbearer": "Cherry Setter",
    "Shovels": "Scoops",
    "Shovel": "Scoop",
    "Shovel Locker": "Scoop Rack",
    "Digs": "Servings",
    "Dig": "Scoop",
    "Digging": "Scooping",
    "Wooden": "Wafer",
    "Copper": "Toffee",
    "Iron": "Nougat",
    "Steel": "Porcelain",
    "Titanium": "Marzipan",
    "Obsidian": "Ganache",
    "Diamond": "Praline",
    "The shovel shattered": "The scoop snapped",
    "Boom.": "A sour burst.",
    "Hints": "Taste Tests",
    "Hint": "Taste Test",
    "Quartermaster": "Pantry",
    "Supplies": "Ingredients",
    "Equipment": "Utensils",
    "Special Equipment": "Special Utensils",
    "Workshop": "Recipe Studio",
    "Upgrades": "Recipe Upgrades",
    "Upgrade": "Refine",
    "Abilities": "Kitchen Skills",
    "Ability": "Kitchen Skill",
    "Purse": "Till",
    "Coins": "Sugar Pennies",
    "Coin": "Sugar Penny",
    "Claims Desk": "Order Desk",
    "Message Board": "Order Board",
    "Contracts": "Orders",
    "Contract": "Order",
    "Challenges": "Bake-Offs",
    "Challenge": "Bake-Off",
    "Finds": "Sweet Collection",
    "Mine Curio": "Sugar Keepsake",
    "Curios": "Confections",
    "Curio": "Confection",
    "Operator Panel": "Chef's Office",
    "Settings": "Kitchen Settings",
    "Ledger": "Recipe Journal",
    "Statistics": "Kitchen Records",
    "Corporate Restructuring": "Reopen the Confectionery",
    "Restructure": "Reopen Confectionery",
    "Delete All Progress": "Erase All Confectionery Progress",
    "High Score": "Finest Batch",
    "District Crew": "Kitchen Crew",
    "District": "Factory Map",
    "Parcels": "Workstations",
    "Parcel": "Workstation",
    "Camp Parcel": "Test Kitchen Site",
    "Establish a Camp": "Open a Test Kitchen",
    "Camp": "Test Kitchen",
    "Field Specification": "Batch Recipe",
    "Field Spec": "Recipe",
    "Field value": "Batch value",
    "Field Cleared": "Tray Cleared",
    "Field": "Tray",
    "Board Setup": "Tray Setup",
    "Boards": "Batches",
    "Board": "Batch",
    "This Run": "This Service",
    "Runs": "Services",
    "Run": "Service",
    "Auto Miners": "Kitchen Assistants",
    "Auto Miner": "Kitchen Assistant",
    "Auto Mine": "Auto Bake",
    "Surveyors": "Recipe Scouts",
    "Surveyor": "Recipe Scout",
    "Excavator": "Scoop Chef",
    "Analyst": "Recipe Analyst",
    "Specialists": "Pastry Chefs",
    "Specialist": "Pastry Chef",
    "Agents": "Kitchen Staff",
    "Agent": "Kitchen Hand",
    "Blueprint Library": "Recipe Library",
    "Blueprints": "Recipes",
    "Blueprint": "Recipe",
    "Probe Charge": "Tasting Spoon",
    "Controlled Blast": "Caramel Popper",
    "Seismic Trap": "Sugar Sieve",
    "Bomb-Bot": "Clockwork Whisk",
    "Mine Encapsulation": "Sugar Cloche",
    "Taller Grid": "Longer Tray",
    "Wider Grid": "Wider Tray",
    "Add Mine": "Add Sour Drop",
    "Add Treasure": "Add Truffle",
    "Improve Shovel": "Improve Scoop",
    "Mine Yield": "Sour Drop Bounty",
    "Better Flags": "Sturdier Cherry Picks",
    "Safety Radius": "Tasting Circle",
    "Chording": "Linked Scooping",
    "Abandoned Yard": "Forgotten Sweetshop",
    "Coal Seam": "Cocoa Cellar",
    "Flooded Quarry": "Syrup Reservoir",
    "Crystal Cavern": "Rock Candy Grotto",
    "Ruined Armory": "Old Utensil Vault",
    "Battlefield": "Burnt Caramel Hall",
    "Abandoned Quarry": "Wafer Quarry",
    "Iron Seam": "Nougat Seam",
    "Collapsed Tunnel": "Crumbled Biscuit Tunnel",
    "Crystal Chamber": "Sugar Crystal Room",
    "Old Military Arsenal": "Old Mixer Store",
    "Gold Vein": "Honeycomb Vein",
    "Unstable Fault": "Brittle Toffee Fault",
    "Loose Sediment": "Loose Crumbs",
    "Bedrock": "Hard Candy Base",
    "Flooded Pocket": "Molasses Pocket",
    "Flag Discipline": "Cherry Discipline",
    "Manual Sweep": "Handmade Batch",
    "Rush Job": "Rush Order",
    "Company": "Confectionery",
    "Inventory": "Utensil Drawer",
    "Sweep the grid": "Sample the tray",
    "Begin sweep": "Begin batch",
    "Arcade controls": "Kitchen controls",
    "Cabinet mode controls": "Kitchen mode controls",
    "Flagged": "Cherry-marked",
    "Max": "Full",
    "READY": "BAKE",
    "RETRY": "REBAKE",
    "DONE": "SERVED",
    "AGAIN": "NEXT",
    "LOCKED": "CLOSED",
    "BACK": "RETURN",
    "✹": "●",
    "⚑": "🍒",
    "✦": "🍬",
    "◆": "❀",
    "⛏": "🥄",
    "★": "♡",
    "▣": "▥",
    "$": "¢",
    "Sweeper inc.": "Sugar works confectionery",
    "Sweeper inc": "Sugar works confectionery",
    "Richer caches": "Richer bonbon batches",
    "Flag locker": "Cherry jar",
    "Shovel locker": "Scoop rack",
    "Special equipment": "Special utensils",
    "Claims desk": "Order desk",
    "Message board": "Order board",
    "Mine curio": "Sugar keepsake",
    "Operator panel": "Chef's office",
    "Corporate restructuring": "Reopen the confectionery",
    "Delete all progress": "Erase all confectionery progress",
    "High score": "Finest batch",
    "District crew": "Kitchen crew",
    "Camp parcel": "Test kitchen site",
    "Establish a camp": "Open a test kitchen",
    "Field specification": "Batch recipe",
    "Field spec": "Recipe",
    "Field cleared": "Tray cleared",
    "Board setup": "Tray setup",
    "This run": "This service",
    "Auto miners": "Kitchen assistants",
    "Auto miner": "Kitchen assistant",
    "Auto mine": "Auto bake",
    "Blueprint library": "Recipe library",
    "Probe charge": "Tasting spoon",
    "Controlled blast": "Caramel popper",
    "Seismic trap": "Sugar sieve",
    "Bomb-bot": "Clockwork whisk",
    "Mine encapsulation": "Sugar cloche",
    "Taller grid": "Longer tray",
    "Wider grid": "Wider tray",
    "Add mine": "Add sour drop",
    "Add treasure": "Add truffle",
    "Improve shovel": "Improve scoop",
    "Mine yield": "Sour drop bounty",
    "Better flags": "Sturdier cherry picks",
    "Safety radius": "Tasting circle",
    "Abandoned yard": "Forgotten sweetshop",
    "Coal seam": "Cocoa cellar",
    "Flooded quarry": "Syrup reservoir",
    "Crystal cavern": "Rock candy grotto",
    "Ruined armory": "Old utensil vault",
    "Abandoned quarry": "Wafer quarry",
    "Iron seam": "Nougat seam",
    "Collapsed tunnel": "Crumbled biscuit tunnel",
    "Crystal chamber": "Sugar crystal room",
    "Old military arsenal": "Old mixer store",
    "Gold vein": "Honeycomb vein",
    "Unstable fault": "Brittle toffee fault",
    "Loose sediment": "Loose crumbs",
    "Flooded pocket": "Molasses pocket",
    "Flag discipline": "Cherry discipline",
    "Manual sweep": "Handmade batch",
    "Rush job": "Rush order",
    "To flag": "To place a cherry marker",
    "Flagging": "Placing cherries",
    "Excavating": "Scooping",
    "Locked": "Closed",
    "Move": "Action",
    "Moves": "Actions",
    "Bronze": "Caramel",
    "Silver": "Vanilla",
    "Gold": "Honey",
    "arcade minesweeper": "candy discovery game",
    "minesweeper": "candy discovery",
    "sweeper inc.": "sugar works confectionery",
    "sweeper inc": "sugar works confectionery",
    "mines": "sour drops",
    "mine": "sour drop",
    "treasures": "truffles",
    "treasure": "truffle",
    "chests": "candy boxes",
    "chest": "candy box",
    "caches": "bonbon batches",
    "cache": "bonbon batch",
    "richer caches": "richer bonbon batches",
    "flags": "cherry markers",
    "flag": "cherry marker",
    "flag locker": "cherry jar",
    "flagbearer": "cherry setter",
    "shovels": "scoops",
    "shovel": "scoop",
    "shovel locker": "scoop rack",
    "digs": "servings",
    "dig": "scoop",
    "digging": "scooping",
    "wooden": "wafer",
    "copper": "toffee",
    "iron": "nougat",
    "steel": "porcelain",
    "titanium": "marzipan",
    "obsidian": "ganache",
    "diamond": "praline",
    "the shovel shattered": "the scoop snapped",
    "boom.": "a sour burst.",
    "hints": "taste tests",
    "hint": "taste test",
    "quartermaster": "pantry",
    "supplies": "ingredients",
    "equipment": "utensils",
    "special equipment": "special utensils",
    "workshop": "recipe studio",
    "upgrades": "recipe upgrades",
    "upgrade": "refine",
    "abilities": "kitchen skills",
    "ability": "kitchen skill",
    "purse": "till",
    "coins": "sugar pennies",
    "coin": "sugar penny",
    "claims desk": "order desk",
    "message board": "order board",
    "contracts": "orders",
    "contract": "order",
    "challenges": "bake-offs",
    "challenge": "bake-off",
    "finds": "sweet collection",
    "mine curio": "sugar keepsake",
    "curios": "confections",
    "curio": "confection",
    "operator panel": "chef's office",
    "settings": "kitchen settings",
    "ledger": "recipe journal",
    "statistics": "kitchen records",
    "corporate restructuring": "reopen the confectionery",
    "restructure": "reopen confectionery",
    "delete all progress": "erase all confectionery progress",
    "high score": "finest batch",
    "district crew": "kitchen crew",
    "district": "factory map",
    "parcels": "workstations",
    "parcel": "workstation",
    "camp parcel": "test kitchen site",
    "establish a camp": "open a test kitchen",
    "camp": "test kitchen",
    "field specification": "batch recipe",
    "field spec": "recipe",
    "field value": "batch value",
    "field cleared": "tray cleared",
    "field": "tray",
    "board setup": "tray setup",
    "boards": "batches",
    "board": "batch",
    "this run": "this service",
    "runs": "services",
    "run": "service",
    "auto miners": "kitchen assistants",
    "auto miner": "kitchen assistant",
    "auto mine": "auto bake",
    "surveyors": "recipe scouts",
    "surveyor": "recipe scout",
    "excavator": "scoop chef",
    "analyst": "recipe analyst",
    "specialists": "pastry chefs",
    "specialist": "pastry chef",
    "agents": "kitchen staff",
    "agent": "kitchen hand",
    "blueprint library": "recipe library",
    "blueprints": "recipes",
    "blueprint": "recipe",
    "probe charge": "tasting spoon",
    "controlled blast": "caramel popper",
    "seismic trap": "sugar sieve",
    "bomb-bot": "clockwork whisk",
    "mine encapsulation": "sugar cloche",
    "taller grid": "longer tray",
    "wider grid": "wider tray",
    "add mine": "add sour drop",
    "add treasure": "add truffle",
    "improve shovel": "improve scoop",
    "mine yield": "sour drop bounty",
    "better flags": "sturdier cherry picks",
    "safety radius": "tasting circle",
    "chording": "linked scooping",
    "abandoned yard": "forgotten sweetshop",
    "coal seam": "cocoa cellar",
    "flooded quarry": "syrup reservoir",
    "crystal cavern": "rock candy grotto",
    "ruined armory": "old utensil vault",
    "battlefield": "burnt caramel hall",
    "abandoned quarry": "wafer quarry",
    "iron seam": "nougat seam",
    "collapsed tunnel": "crumbled biscuit tunnel",
    "crystal chamber": "sugar crystal room",
    "old military arsenal": "old mixer store",
    "gold vein": "honeycomb vein",
    "unstable fault": "brittle toffee fault",
    "loose sediment": "loose crumbs",
    "bedrock": "hard candy base",
    "flooded pocket": "molasses pocket",
    "flag discipline": "cherry discipline",
    "manual sweep": "handmade batch",
    "rush job": "rush order",
    "company": "confectionery",
    "inventory": "utensil drawer",
    "sweep the grid": "sample the tray",
    "begin sweep": "begin batch",
    "arcade controls": "kitchen controls",
    "cabinet mode controls": "kitchen mode controls",
    "flagged": "cherry-marked",
    "max": "full",
    "to flag": "to place a cherry marker",
    "flagging": "placing cherries",
    "excavating": "scooping",
    "locked": "closed",
    "move": "action",
    "moves": "actions",
    "bronze": "caramel",
    "silver": "vanilla",
    "gold": "honey"
  }
});
