// Presentation only. Title-case entries precede lowercase variants.
ThemeKit.register({
  "id": "tomb-expedition",
  "name": "Tomb Expedition",
  "author": "Codex",
  "title": "Tomb Expedition | Lotus Expedition Society",
  "fonts": "https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600;700&family=Source+Sans+3:wght@400;600;700&display=swap",
  "labels": {
    "#use-hint": "Lantern<br>Glimpse",
    "#auto-miners-button": "Auto<br>Dig",
    "#district-button": "Dig-Site<br>Map",
    ".marquee h1": "Tomb Expedition"
  },
  "phrases": {
    "Sweeper Inc.": "Lotus Expedition Society",
    "Sweeper Inc": "Lotus Expedition Society",
    "Mines": "Curse Traps",
    "Mine": "Curse Trap",
    "Treasures": "Relics",
    "Treasure": "Relic",
    "Chests": "Reliquaries",
    "Chest": "Reliquary",
    "Caches": "Relic Hoards",
    "Cache": "Relic Hoard",
    "Richer Caches": "Richer Relic Hoards",
    "Flags": "Warning Stakes",
    "Flag": "Warning Stake",
    "Flag Locker": "Stake Case",
    "Flagbearer": "Stake Keeper",
    "Shovels": "Trowels",
    "Shovel": "Trowel",
    "Shovel Locker": "Trowel Case",
    "Digs": "Brushstrokes",
    "Dig": "Brush",
    "Digging": "Brushing",
    "Wooden": "Reed",
    "Copper": "Bronze",
    "Iron": "Tempered",
    "Steel": "Gilded",
    "Titanium": "Lapis",
    "Obsidian": "Onyx",
    "Diamond": "Sunstone",
    "The shovel shattered": "The trowel shattered",
    "Boom.": "A curse strikes.",
    "Hints": "Lantern Glimpses",
    "Hint": "Lantern Glimpse",
    "Quartermaster": "Supply Tent",
    "Supplies": "Dig Supplies",
    "Equipment": "Instruments",
    "Special Equipment": "Expedition Instruments",
    "Workshop": "Restoration Tent",
    "Upgrades": "Improvements",
    "Upgrade": "Improve",
    "Abilities": "Field Techniques",
    "Ability": "Field Technique",
    "Purse": "Expedition Fund",
    "Coins": "Gold Pieces",
    "Coin": "Gold Piece",
    "Claims Desk": "Society Office",
    "Message Board": "Dispatch Board",
    "Contracts": "Commissions",
    "Contract": "Commission",
    "Challenges": "Society Trials",
    "Challenge": "Society Trial",
    "Finds": "Antiquities",
    "Mine Curio": "Royal Keepsake",
    "Curios": "Keepsakes",
    "Curio": "Keepsake",
    "Operator Panel": "Expedition Office",
    "Settings": "Preferences",
    "Ledger": "Expedition Journal",
    "Statistics": "Expedition Records",
    "Corporate Restructuring": "Renew the Expedition",
    "Restructure": "Renew Expedition",
    "Delete All Progress": "Erase All Expedition Progress",
    "High Score": "Greatest Discovery",
    "District Crew": "Dig-Site Crew",
    "District": "Dig-Site Map",
    "Parcels": "Dig Sites",
    "Parcel": "Dig Site",
    "Camp Parcel": "Base Tent Site",
    "Establish a Camp": "Pitch a Base Tent",
    "Camp": "Base Tent",
    "Field Specification": "Excavation Plan",
    "Field Spec": "Dig Plan",
    "Field value": "Relic value",
    "Field Cleared": "Chamber Cleared",
    "Field": "Chamber",
    "Board Setup": "Chamber Setup",
    "Boards": "Excavations",
    "Board": "Excavation",
    "This Run": "This Expedition",
    "Runs": "Expeditions",
    "Run": "Expedition",
    "Auto Miners": "Dig Assistants",
    "Auto Miner": "Dig Assistant",
    "Auto Mine": "Auto Dig",
    "Surveyors": "Cartographers",
    "Surveyor": "Cartographer",
    "Excavator": "Brush Keeper",
    "Analyst": "Inscription Reader",
    "Specialists": "Scholars",
    "Specialist": "Scholar",
    "Agents": "Society Members",
    "Agent": "Society Member",
    "Blueprint Library": "Papyrus Archive",
    "Blueprints": "Papyri",
    "Blueprint": "Papyrus",
    "Probe Charge": "Sounding Rod",
    "Controlled Blast": "Sealed Powder Charge",
    "Seismic Trap": "Tremor Bell",
    "Bomb-Bot": "Clockwork Scarab",
    "Mine Encapsulation": "Curse Seal",
    "Taller Grid": "Deeper Chamber",
    "Wider Grid": "Wider Chamber",
    "Add Mine": "Add Curse Trap",
    "Add Treasure": "Add Relic",
    "Improve Shovel": "Improve Trowel",
    "Mine Yield": "Curse Bounty",
    "Better Flags": "Stronger Stakes",
    "Safety Radius": "Warding Circle",
    "Chording": "Linked Brushing",
    "Abandoned Yard": "Forgotten Courtyard",
    "Coal Seam": "Obsidian Gallery",
    "Flooded Quarry": "Flooded Necropolis",
    "Crystal Cavern": "Lapis Grotto",
    "Ruined Armory": "Pharaoh's Guardhouse",
    "Battlefield": "Chariot Burial Ground",
    "Abandoned Quarry": "Desert Quarry",
    "Iron Seam": "Bronze Gallery",
    "Collapsed Tunnel": "Fallen Passage",
    "Crystal Chamber": "Lapis Chamber",
    "Old Military Arsenal": "Royal Weapon Vault",
    "Gold Vein": "Gilded Burial Vault",
    "Unstable Fault": "Fractured Tomb Wall",
    "Loose Sediment": "Windblown Sand",
    "Bedrock": "Granite Foundation",
    "Flooded Pocket": "Hidden Cistern",
    "Flag Discipline": "Stake Discipline",
    "Manual Sweep": "Hand Excavation",
    "Rush Job": "Race the Sunset",
    "Company": "Expedition Society",
    "Inventory": "Instrument Case",
    "Sweep the grid": "Explore the chamber",
    "Begin sweep": "Begin excavation",
    "Arcade controls": "Expedition controls",
    "Cabinet mode controls": "Expedition mode controls",
    "Flagged": "Staked",
    "Max": "Full",
    "READY": "ENTER",
    "RETRY": "RETRY DIG",
    "DONE": "CLEARED",
    "AGAIN": "DIG AGAIN",
    "LOCKED": "SEALED",
    "BACK": "RETURN",
    "✹": "☥",
    "⚑": "⚐",
    "✦": "◈",
    "◆": "❖",
    "⛏": "⚒",
    "★": "☼",
    "▣": "▤",
    "$": "G ",
    "Sweeper inc.": "Lotus expedition society",
    "Sweeper inc": "Lotus expedition society",
    "Richer caches": "Richer relic hoards",
    "Flag locker": "Stake case",
    "Shovel locker": "Trowel case",
    "Special equipment": "Expedition instruments",
    "Claims desk": "Society office",
    "Message board": "Dispatch board",
    "Mine curio": "Royal keepsake",
    "Operator panel": "Expedition office",
    "Corporate restructuring": "Renew the expedition",
    "Delete all progress": "Erase all expedition progress",
    "High score": "Greatest discovery",
    "District crew": "Dig-site crew",
    "Camp parcel": "Base tent site",
    "Establish a camp": "Pitch a base tent",
    "Field specification": "Excavation plan",
    "Field spec": "Dig plan",
    "Field cleared": "Chamber cleared",
    "Board setup": "Chamber setup",
    "This run": "This expedition",
    "Auto miners": "Dig assistants",
    "Auto miner": "Dig assistant",
    "Auto mine": "Auto dig",
    "Blueprint library": "Papyrus archive",
    "Probe charge": "Sounding rod",
    "Controlled blast": "Sealed powder charge",
    "Seismic trap": "Tremor bell",
    "Bomb-bot": "Clockwork scarab",
    "Mine encapsulation": "Curse seal",
    "Taller grid": "Deeper chamber",
    "Wider grid": "Wider chamber",
    "Add mine": "Add curse trap",
    "Add treasure": "Add relic",
    "Improve shovel": "Improve trowel",
    "Mine yield": "Curse bounty",
    "Better flags": "Stronger stakes",
    "Safety radius": "Warding circle",
    "Abandoned yard": "Forgotten courtyard",
    "Coal seam": "Obsidian gallery",
    "Flooded quarry": "Flooded necropolis",
    "Crystal cavern": "Lapis grotto",
    "Ruined armory": "Pharaoh's guardhouse",
    "Abandoned quarry": "Desert quarry",
    "Iron seam": "Bronze gallery",
    "Collapsed tunnel": "Fallen passage",
    "Crystal chamber": "Lapis chamber",
    "Old military arsenal": "Royal weapon vault",
    "Gold vein": "Gilded burial vault",
    "Unstable fault": "Fractured tomb wall",
    "Loose sediment": "Windblown sand",
    "Flooded pocket": "Hidden cistern",
    "Flag discipline": "Stake discipline",
    "Manual sweep": "Hand excavation",
    "Rush job": "Race the sunset",
    "To flag": "To place a warning stake",
    "Flagging": "Placing stakes",
    "Excavating": "Brushing",
    "Locked": "Sealed",
    "Move": "Action",
    "Moves": "Actions",
    "Bronze": "Terracotta",
    "Silver": "Alabaster",
    "Gold": "Gilded",
    "arcade minesweeper": "tomb exploration game",
    "minesweeper": "chamber exploration",
    "sweeper inc.": "lotus expedition society",
    "sweeper inc": "lotus expedition society",
    "mines": "curse traps",
    "mine": "curse trap",
    "treasures": "relics",
    "treasure": "relic",
    "chests": "reliquaries",
    "chest": "reliquary",
    "caches": "relic hoards",
    "cache": "relic hoard",
    "richer caches": "richer relic hoards",
    "flags": "warning stakes",
    "flag": "warning stake",
    "flag locker": "stake case",
    "flagbearer": "stake keeper",
    "shovels": "trowels",
    "shovel": "trowel",
    "shovel locker": "trowel case",
    "digs": "brushstrokes",
    "dig": "brush",
    "digging": "brushing",
    "wooden": "reed",
    "copper": "bronze",
    "iron": "tempered",
    "steel": "gilded",
    "titanium": "lapis",
    "obsidian": "onyx",
    "diamond": "sunstone",
    "the shovel shattered": "the trowel shattered",
    "boom.": "a curse strikes.",
    "hints": "lantern glimpses",
    "hint": "lantern glimpse",
    "quartermaster": "supply tent",
    "supplies": "dig supplies",
    "equipment": "instruments",
    "special equipment": "expedition instruments",
    "workshop": "restoration tent",
    "upgrades": "improvements",
    "upgrade": "improve",
    "abilities": "field techniques",
    "ability": "field technique",
    "purse": "expedition fund",
    "coins": "gold pieces",
    "coin": "gold piece",
    "claims desk": "society office",
    "message board": "dispatch board",
    "contracts": "commissions",
    "contract": "commission",
    "challenges": "society trials",
    "challenge": "society trial",
    "finds": "antiquities",
    "mine curio": "royal keepsake",
    "curios": "keepsakes",
    "curio": "keepsake",
    "operator panel": "expedition office",
    "settings": "preferences",
    "ledger": "expedition journal",
    "statistics": "expedition records",
    "corporate restructuring": "renew the expedition",
    "restructure": "renew expedition",
    "delete all progress": "erase all expedition progress",
    "high score": "greatest discovery",
    "district crew": "dig-site crew",
    "district": "dig-site map",
    "parcels": "dig sites",
    "parcel": "dig site",
    "camp parcel": "base tent site",
    "establish a camp": "pitch a base tent",
    "camp": "base tent",
    "field specification": "excavation plan",
    "field spec": "dig plan",
    "field value": "relic value",
    "field cleared": "chamber cleared",
    "field": "chamber",
    "board setup": "chamber setup",
    "boards": "excavations",
    "board": "excavation",
    "this run": "this expedition",
    "runs": "expeditions",
    "run": "expedition",
    "auto miners": "dig assistants",
    "auto miner": "dig assistant",
    "auto mine": "auto dig",
    "surveyors": "cartographers",
    "surveyor": "cartographer",
    "excavator": "brush keeper",
    "analyst": "inscription reader",
    "specialists": "scholars",
    "specialist": "scholar",
    "agents": "society members",
    "agent": "society member",
    "blueprint library": "papyrus archive",
    "blueprints": "papyri",
    "blueprint": "papyrus",
    "probe charge": "sounding rod",
    "controlled blast": "sealed powder charge",
    "seismic trap": "tremor bell",
    "bomb-bot": "clockwork scarab",
    "mine encapsulation": "curse seal",
    "taller grid": "deeper chamber",
    "wider grid": "wider chamber",
    "add mine": "add curse trap",
    "add treasure": "add relic",
    "improve shovel": "improve trowel",
    "mine yield": "curse bounty",
    "better flags": "stronger stakes",
    "safety radius": "warding circle",
    "chording": "linked brushing",
    "abandoned yard": "forgotten courtyard",
    "coal seam": "obsidian gallery",
    "flooded quarry": "flooded necropolis",
    "crystal cavern": "lapis grotto",
    "ruined armory": "pharaoh's guardhouse",
    "battlefield": "chariot burial ground",
    "abandoned quarry": "desert quarry",
    "iron seam": "bronze gallery",
    "collapsed tunnel": "fallen passage",
    "crystal chamber": "lapis chamber",
    "old military arsenal": "royal weapon vault",
    "gold vein": "gilded burial vault",
    "unstable fault": "fractured tomb wall",
    "loose sediment": "windblown sand",
    "bedrock": "granite foundation",
    "flooded pocket": "hidden cistern",
    "flag discipline": "stake discipline",
    "manual sweep": "hand excavation",
    "rush job": "race the sunset",
    "company": "expedition society",
    "inventory": "instrument case",
    "sweep the grid": "explore the chamber",
    "begin sweep": "begin excavation",
    "arcade controls": "expedition controls",
    "cabinet mode controls": "expedition mode controls",
    "flagged": "staked",
    "max": "full",
    "to flag": "to place a warning stake",
    "flagging": "placing stakes",
    "excavating": "brushing",
    "locked": "sealed",
    "move": "action",
    "moves": "actions",
    "bronze": "terracotta",
    "silver": "alabaster",
    "gold": "gilded"
  }
});
